---
- name: End API Session
  ansible.builtin.uri:
    url: "{{ http_protocol | default('https') | string }}://{{ nfc_pb_glpi_host }}/apirest.php/killSession"
    method: GET
    body: ''
    status_code: 200
    headers:
      App-Token: "{{ nfc_pb_glpi_app_token }}"
      Session-Token: "{{ nfc_pb_glpi_session.valid_id }}"
    validate_certs: "{{ nfc_pb_glpi_validate_certs | default(true) | bool }}"
  no_log: "{{ nfc_pb_glpi_no_log_sensitive_data | default(true) | bool }}"


# Ensure not saved as facts
- name: Clear Variables
  ansible.builtin.set_fact:
    nfc_pb_glpi_session: null
    nfc_pb_glpi_host: null
    nfc_pb_glpi_app_token: null
    nfc_pb_glpi_user_token: null
