---

- name: "{{ task_name_module | default('MariaDB Database Action') }}"
  community.postgresql.postgresql_db:
    login_user: "{{ nfc_pb_postgres_username }}"
    login_password: "{{ nfc_pb_postgres_password }}"

    login_host: "{{ module_database.host.name }}"
    port: "{{ module_database.host.port | default(omit) }}"

    login_unix_socket: "{{ module_database.host.socket | default(omit) }}"

    name: "{{ module_database.name }}"
    state: "{{ module_database.state }}"

    force: "{{ module_database.force | default(omit) }}"
    target: "{{ module_database.target | default(omit) }}"

  become: "{{ module_database.become | default(omit) }}"
  delegate_to: "{{ module_database.delegate_to | default(omit) }}"
  no_log: "{{ module_database.no_log | default(false) | bool }}"
  retries: "{{ module_database.retries | default(omit) }}"
