---

include:
  - project: nofusscomputing/projects/gitlab-ci
    ref: development
    file:
      - .gitlab-ci_common.yaml
      - automation/.gitlab-ci.ansible.yaml


variables:
  GIT_SUBMODULE_STRATEGY: recursive
  #GIT_SYNC_URL: "https://$GITHUB_USERNAME_ROBOT:$GITHUB_TOKEN_ROBOT@github.com/NoFussComputing/ansible_playbooks.git"
  MY_PROJECT_ID: "46364551"
  PAGES_ENVIRONMENT_PATH: projects/ansible_playbooks/