---
- name: AWX / Tower Setup
  hosts: localhost
  become: false
  gather_facts: true

  tasks:


    - name: Organizations
      ansible.builtin.include_tasks:
        file: tasks/awx/organization.yaml
      loop: "{{ my_awx_config.organizations }}" # Fix as this var should be dynamic
      loop_control:
        loop_var: nfc_pb_awx_organization


  vars:
    ansible_connection: local
    nfc_pb_awx_tower_template:
      - name: "AWX / Tower Configure"
        ask_tags_on_launch: false
        ask_inventory_on_launch: true
        ask_credential_on_launch: true
        description: Configure AWX from Inventory
        execution_environment: "No Fuss Computing EE"
        job_type: "run"
        labels:
          - awx
          - configure
        # credentials:
        #   - "Local"
        verbosity: 2
        use_fact_cache: true
        survey_enabled: true
        survey_spec: |
          {
            "name": "",
            "spec": [
              {
                "max": 1024,
                "min": 3,
                "type": "text",
                "choices": "",
                "default": "my_awx_config",
                "required": true,
                "variable": "nfc_pb_awx_config_variable",
                "new_question": true,
                "question_name": "Inventory Variable",
                "question_description": "The Variable in the Inventory the AWX config is under"
              }
            ],
            "description": ""
          }


#################################################################################################################################

# turned off until can figure out instances
    # - name: Instance group setup
    #   awx.awx.instance_group:
    #     name: "{{ item[1].name }}"
    #     controller_host: "{{ item[0].controller_host | default(omit) }}"
    #     controller_oauthtoken: "{{ item[0].controller_oauthtoken| default(omit) }}"
    #     controller_username: "{{ item[0].controller_username | default(omit) }}"
    #     controller_password: "{{ item[0].controller_password| default(omit) }}"
    #     max_concurrent_jobs: "{{ item[0].max_concurrent_jobs | default('0') }}"
    #     max_forks: "{{ item[0].max_forks | default('0') }}"
    #     state: "{{ item[1].state | default('present') }}"
    #   when: nfc_pb_awx_config is defined and nfc_pb_awx_config.organizations is defined and item[1]|length > 0
    #   #with_items: "{{ awx.organizations }}.instance_groups"
    #   # with_list: "{{ awx.organizations.instance_groups }}"
    #   with_subelements:
    #     - "{{awx_config.organizations}}"
    #     - instance_groups


    # - name: Update all inventory sources
    #   awx.awx.inventory_source_update:
    #     name: "{{ item[1].name }}"
    #     inventory: "{{ item[1].name }}"
    #     organization: "{{ item[0].name }}"
    #     controller_host: "{{ nfc_pb_awx_controller_host | default(omit) }}"
    #     controller_oauthtoken: "{{ nfc_pb_awx_controller_oauthtoken | default(omit) }}"
    #     controller_username: "{{ nfc_pb_awx_controller_username | default(omit) }}"
    #     controller_password: "{{ nfc_pb_awx_controller_password | default(omit) }}"
    #   with_subelements:
    #     - "{{ nfc_pb_awx_config_variable.organizations }}"
    #     - projects
    #   when: nfc_pb_awx_config is defined and nfc_pb_awx_config.organizations is defined and item[1] | length > 0
    #   # no_log: true
    #   diff: true
    #   tags:
    #     - inventory_source_update
    #     - sync
    #     - inventory
    #     - rbac

    # #
    # # required pip modules pytz, python-dateutil
    # #
    # - name: Schedule configuration
    #   awx.awx.schedule:
    #     controller_host: "{{ nfc_pb_awx_controller_host | default(omit) }}"
    #     controller_oauthtoken: "{{ nfc_pb_awx_controller_oauthtoken | default(omit) }}"
    #     controller_username: "{{ nfc_pb_awx_controller_username | default(omit) }}"
    #     controller_password: "{{ nfc_pb_awx_controller_password | default(omit) }}"
    #     name: "{{ item[1].name }}"
    #     state: "{{ item[1].state | default('present') }}"
    #     scm_branch: "{{ item[1].scm_branch | default(omit) }}"
    #     unified_job_template: "{{ item[1].template }}"
    #     job_tags: "{{ item[1].job_tags | default(omit) }}"
    #     job_type: "{{ item[1].job_type }}"
    #     rrule: "{{ query('awx.awx.schedule_rrule', item[1].schedule.terms, every=item[1].schedule.every, timezone=item[1].schedule.timezone) }}" # "{{ item[1].schedule }}"
    #   with_subelements:
    #     - "{{ nfc_pb_awx_config.organizations }}"
    #     - schedules
    #   # no_log: true
    #   diff: true
    #   tags:
    #     - schedule
