---
- name: Git Configuration as Code
  hosts: localhost
  gather_facts: true


  roles:
    - name: Configure git from Code
      role: git_configuration


  vars:
    ansible_connection: local
    nfc_pb_awx_tower_template:
      - name: "Configure Gitlab / Github Repositories"
        ask_credential_on_launch: true
        ask_tags_on_launch: true
        ask_inventory_on_launch: true
        description: |
          Create/Configure Gitlab or Github repositories from an inventory.
          Available tags:
            'gitlab' configure a Gitlab repository,
            'github' configure a Github repository.
        execution_environment: "No Fuss Computing EE"
        job_type: "run"
        job_tags: gitlab, github
        labels:
          - config
          - git
          - gitlab
          - github
        # credentials:
        #   - "Local"
        verbosity: 2
        use_fact_cache: true
        survey_enabled: false

      - name: "Webhook/gitlab/Create Artifact"
        ask_credential_on_launch: false
        ask_limit_on_launch: false
        ask_instance_groups_on_launch: false
        ask_inventory_on_launch: true
        ask_job_type_on_launch: false
        ask_tags_on_launch: false
        ask_variables_on_launch: false
        description: |
          This job template is intended to create an Artifact
          from an inbound gitlab webhook.
          Available tags:
            'gitlab_webhook' Create an Artifact with webhook data,
        execution_environment: "No Fuss Computing EE"
        job_type: "run"
        job_tags: gitlab_webhook
        labels:
          - automation
          - gitlab
          - webhook
        verbosity: 1
        use_fact_cache: true
        survey_enabled: false
