---
- name: Kubernetes Group and sub-groups
  hosts: "{{ groups.kubernetes }}"
  gather_facts: false


  roles:

    - name: Common tasks
      role: nfc_common
      vars:
        common_gather_facts: true

  vars:
    nfc_pb_awx_tower_template:
      - name: "Kubernetes"
        ask_credential_on_launch: true
        ask_tags_on_launch: true
        ask_limit_on_launch: true
        ask_variables_on_launch: true
        description: |
          Playbook to Install/Configure Kubernetes using configuration
          from code.
        execution_environment: "No Fuss Computing EE"
        job_type: "run"
        labels:
          - cluster
          - k3s
          - kubernetes
        verbosity: 2
        use_fact_cache: true
        survey_enabled: false

- name: Kubernetes Master
  import_playbook: kubernetes/master.yaml

- name: Kubernetes Worker
  import_playbook: kubernetes/worker.yaml


