---
- name: Host Role Configuration / Deployment
  hosts: |-
    {%- if nfc_pb_host is defined -%}
      {{ nfc_pb_host }}
    {%- else -%}
      all
    {%- endif %}
  become: false
  gather_facts: false


  pre_tasks:


    - name: Confirm Existance of NetBox Connection Variables
      ansible.builtin.assert:
        that:
          - lookup('env', 'NETBOX_API') != ''
          - lookup('env', 'NETBOX_TOKEN') != ''
        msg: "'NETBOX_API' and 'NETBOX_TOKEN' environmental variables must be set"
      tags:
        - always


    - name: Fetch DCIM ID from NetBox
      ansible.builtin.uri:
        url: |-
          {{ lookup('env', 'NETBOX_API') }}/api/
          {%- if is_virtual -%}
            virtualization/virtual-machines
          {%- else -%}
            dcim/devices
          {%- endif -%}
          /?name={{ inventory_hostname }}&serial={{ serial }}
        method: GET
        headers:
          Authorization: Token {{ lookup('env', 'NETBOX_TOKEN') }}
        return_content: true
        validate_certs: "{{ lookup('env', 'NETBOX_VALIDATE_CERTS') | default(true) | bool }}"
      check_mode: false
      delegate_to: localhost
      no_log: true    # Contains a secret that logging shows
      register: host_details
      tags:
        - always


    - name: Fetch Rendered Config from NetBox
      ansible.builtin.uri:
        url: |-
          {{ lookup('env', 'NETBOX_API') }}/api/
          {%- if is_virtual -%}
            virtualization/virtual-machines
          {%- else -%}
            dcim/devices
          {%- endif -%}
          /{{ host_details.json.results[0].id }}/render-config/
        method: POST
        headers:
          Authorization: Token {{ lookup('env', 'NETBOX_TOKEN') }}
        return_content: true
        validate_certs: "{{ lookup('env', 'NETBOX_VALIDATE_CERTS') | default(true) | bool }}"
      check_mode: false
      delegate_to: localhost
      no_log: true    # Contains a secret that logging shows
      register: host_configuration
      tags:
        - always


    - name: TRACE Rendered Config
      ansible.builtin.debug:
        msg: "{{ host_configuration.json.content | from_yaml }}"
      check_mode: true
      tags:
        - always


    - name: Try / Catch
      block:


        - name: Save Vars to temp file so they can be loaded as hostvars
          ansible.builtin.copy:
            content: "{{ host_configuration.json.content | from_yaml | to_nice_json(indent=0) }}"
            dest: "/tmp/vars_{{ inventory_hostname }}.json"
            mode: '777'
          changed_when: false
          check_mode: false
          delegate_to: localhost
          tags:
            - always


        - name: Load Vars as hostvars
          ansible.builtin.include_vars:
            file: "/tmp/vars_{{ inventory_hostname }}.json"
          check_mode: false
          delegate_to: localhost
          tags:
            - always


      always:


        - name: Clean tmp var files
          ansible.builtin.file:
            path: "/tmp/vars_{{ inventory_hostname }}.json"
            state: absent
          changed_when: false
          check_mode: false
          delegate_to: localhost
          tags:
            - always


    - name: Role Validation
      ansible.builtin.include_tasks:
        file: tasks/role/validation.yaml
      tags:
        - always


  tasks:

    - name: TRACE
      ansible.builtin.debug:
        msg: "{{ role }}"
      check_mode: false
      tags:
        - always


    - name: "Ansible Role - {{ role_map[role].name }}"
      ansible.builtin.include_role:
        name: "{{ role_map[role].name }}"
        tasks_from: "{{ role_map[role].tasks_from | default(omit) }}"
      tags:
        - never
        - ansible_role


  vars:

    nfc_pb_awx_tower_template:

      - name: "Playbook/Role/Ansible"
        ask_tags_on_launch: false
        ask_inventory_on_launch: true
        ask_credential_on_launch: true
        ask_limit_on_launch: true
        description: Run an Ansible Role against a host.
        execution_environment: "No Fuss Computing EE"
        job_type: "check"
        job_tags: ansible_role
        labels:
          - initial
          - onboarding
          - role
          - soe
        use_fact_cache: true
