---
- name: Add Credential Type
  awx.awx.credential_type:
    controller_host: "{{ nfc_pb_awx_controller_host | default(omit) }}"
    controller_oauthtoken: "{{ nfc_pb_awx_controller_oauthtoken | default(omit) }}"
    controller_username: "{{ nfc_pb_awx_controller_username | default(omit) }}"
    controller_password: "{{ nfc_pb_awx_controller_password | default(omit) }}"
    validate_certs: "{{ validate_certs | default(true) }}"

    name: "{{ nfc_pb_awx_credential_type.name }}"
    new_name: "{{ nfc_pb_awx_credential_type.new_name | default(omit) }}"
    description: "{{ nfc_pb_awx_credential_type.description | default('') }}"
    kind: "{{ nfc_pb_awx_credential_type.kind | default('cloud') }}"
    inputs: "{{ nfc_pb_awx_credential_type.inputs | from_yaml }}"
    injectors: "{{ nfc_pb_awx_credential_type.injectors | from_yaml }}"
    state: "{{ nfc_pb_awx_credential_type.state | default('present') }}"
  # no_log: true
  diff: true
