---
- name: Add Credential
  awx.awx.credential:
    controller_host: "{{ nfc_pb_awx_controller_host | default(omit) }}"
    controller_oauthtoken: "{{ nfc_pb_awx_controller_oauthtoken | default(omit) }}"
    controller_username: "{{ nfc_pb_awx_controller_username | default(omit) }}"
    controller_password: "{{ nfc_pb_awx_controller_password | default(omit) }}"
    validate_certs: "{{ validate_certs | default(true) }}"

    name: "{{ nfc_pb_awx_credential.name }}"
    new_name: "{{ nfc_pb_awx_credential.new_name | default(omit) }}"
    copy_from: "{{ nfc_pb_awx_credential.copy_from | default(omit) }}"
    description: "{{ nfc_pb_awx_credential.description | default(omit) }}"
    organization: "{{ nfc_pb_awx_credential.organization | default(omit) }}"
    credential_type: "{{ nfc_pb_awx_credential.credential_type | default(omit) }}"
    inputs: "{{ nfc_pb_awx_credential.inputs | default(omit) }}"
    update_secrets: "{{ nfc_pb_awx_credential.update_secrets | default(true) }}"
    user: "{{ nfc_pb_awx_credential.user | default(omit) }}"
    team: "{{ nfc_pb_awx_credential.team | default(omit) }}"
    state: "{{ nfc_pb_awx_credential.state | default('present') }}"
  delegate_to: localhost
  retries: 2
  run_once: true
  vars:
    ansible_connection: local
