---

- name: Job Template
  block:
    # - name: Debug
    #   ansible.builtin.debug:
    #     msg:
    #       - "{{ nfc_pb_awx_playbook_filename }}"
    #       - "{{ nfc_pb_awx_job_template }}"
    #       - "{{ nfc_pb_awx_job_template_name | default('Not Yet Defined') }}"

    # - name: Create fact from Playbook
    #   ansible.builtin.set_fact:
    #     playbook_contents: "{{ lookup('file', nfc_pb_awx_playbook_filename) | from_yaml }}"
    #   when: nfc_pb_awx_playbook_filename | default('') != ''
    #   failed_when: false


    # - name: Job Template from Playbook
    #   ansible.builtin.set_fact:
    #     # playbook_contents: "{{ playbook_contents[0] }}"
    #     # nfc_pb_awx_name: "{{ playbook_contents[0].name }}"
    #     nfc_pb_awx_tower_template: "{{ nfc_pb_awx_job_template.vars.nfc_pb_awx_tower_template }}"
    #   when: playbook_contents[0].vars.nfc_pb_awx_tower_template | default([]) | length | int > 0
    #   loop: "{{ playbook_contents }}"
    #   loop_control:
    #     loop_var: job_template
    #   failed_when: false

    - name: Create Labels
      awx.awx.label:
        controller_host: "{{ nfc_pb_awx_controller_host | default(omit) }}"
        controller_oauthtoken: "{{ nfc_pb_awx_controller_oauthtoken | default(omit) }}"
        controller_username: "{{ nfc_pb_awx_controller_username | default(omit) }}"
        controller_password: "{{ nfc_pb_awx_controller_password | default(omit) }}"
        name: "{{ item }}"
        organization: "{{ nfc_pb_awx_organization.name }}"
        state: present
        validate_certs: "{{ validate_certs | default(true) }}"
      loop: "{{ nfc_pb_awx_job_template.labels | default([]) }}"


    - name: "Configure Job Template {{ nfc_pb_awx_playbook_dir | default('') }}{{ nfc_pb_awx_playbook_filename }}"
      awx.awx.job_template:
        name: "{{ nfc_pb_awx_job_template.name }}"
        description: "{{ nfc_pb_awx_job_template.description | default(omit) }}"
        controller_host: "{{ nfc_pb_awx_controller_host | default(omit) }}"
        controller_oauthtoken: "{{ nfc_pb_awx_controller_oauthtoken | default(omit) }}"
        controller_username: "{{ nfc_pb_awx_controller_username | default(omit) }}"
        controller_password: "{{ nfc_pb_awx_controller_password | default(omit) }}"
        execution_environment: "{{ nfc_pb_awx_job_template.execution_environment | default(omit) }}"
        forks: "{{ nfc_pb_awx_job_template.forks| default(1) }}"
        job_type: "{{ nfc_pb_awx_job_template.job_type | default('run') }}"
        job_tags: "{{ nfc_pb_awx_job_template.job_tags | default(omit) }}"
        organization: "{{ nfc_pb_awx_organization.name }}"
        # inventory: "{{ nfc_pb_awx_inventory.name | default(omit) }}"
        project: "{{ nfc_pb_awx_project.name }}"
        playbook: "{{ nfc_pb_awx_project.playbook_path | default('') }}{{ nfc_pb_awx_playbook_filename }}"
        # scm_branch: "{{ nfc_pb_awx_branch }}"
        ask_tags_on_launch: "{{ nfc_pb_awx_job_template.ask_tags_on_launch | default(false) | bool }}"
        ask_inventory_on_launch: "{{ nfc_pb_awx_job_template.ask_inventory_on_launch | default(true) | bool }}"
        credentials: "{{ nfc_pb_awx_job_template.credentials | default(omit) }}"
        state: "{{ nfc_pb_awx_job_template.state | default('present') }}"
        survey_enabled: "{{ nfc_pb_awx_job_template.survey_enabled | default(false) | bool }}"
        # survey_spec: "{{ nfc_pb_awx_job_template.survey_spec | from_yaml | to_json | default(omit) }}"
        survey_spec: >-
          {%- if nfc_pb_awx_job_template.survey_spec | default ('') == '' -%}
          {{ omit }}
          {%- else -%}
          {{ nfc_pb_awx_job_template.survey_spec | from_yaml | to_json }}
          {%- endif -%}
        labels: "{{ nfc_pb_awx_job_template.labels | default(omit) }}"
        verbosity: "{{ nfc_pb_awx_job_template.verbosity | default(2) }}"
        ask_scm_branch_on_launch: "{{ nfc_pb_awx_job_template.ask_scm_branch_on_launch | default(false) | bool }}"
        ask_limit_on_launch: "{{ nfc_pb_awx_job_template.ask_limit_on_launch | default(true) | bool }}"
        ask_job_type_on_launch: "{{ nfc_pb_awx_job_template.ask_job_type_on_launch | default(true) | bool }}"
        ask_credential_on_launch: "{{ nfc_pb_awx_job_template.ask_credential_on_launch | default(false) | bool }}"
        ask_variables_on_launch: "{{ nfc_pb_awx_job_template.ask_credential_on_launch | default(false) | bool }}"
        use_fact_cache: "{{ nfc_pb_awx_job_template.use_fact_cache | default(true) | bool }}"
        validate_certs: "{{ validate_certs | default(true) }}"
      # no_log: true
      # when: nfc_pb_awx_tower_template | default('') != ''
      diff: true


    - name: "RBAC - {{ nfc_pb_awx_organization.name }}/Project/{{ nfc_pb_awx_project.name }}/Job/{{ nfc_pb_awx_job_template.name }}"
      ansible.builtin.include_tasks:
        file: tasks/awx/rbac.yaml
      loop: "{{ nfc_pb_awx_project.rbac.job | default([]) | list }}"
      loop_control:
        loop_var: nfc_pb_awx_rbac
      #when: nfc_pb_awx_project.playbook_path | default('') != ''
      vars:
        nfc_pb_awx_job_template_name: "{{ nfc_pb_awx_job_template.name }}"


    - name: Add Credential Type from Playbook template
      ansible.builtin.include_tasks:
        file: tasks/awx/credential_type.yaml
      loop: "{{ nfc_pb_awx_project.credential_types | default([]) | list }}"
      loop_control:
        loop_var: nfc_pb_awx_credential_type
