---
- name: >-
    "RBAC Config {{ awx_organization.name }}/{%- if awx_inventory.name | default('') != '' -%}
    inventory/{{ awx_inventory.name }}{% else %}project/{{ awx_project.name }}{%- endif -%}/
    {%- if awx_rbac.type == 'team' -%}Team{%- else -%}User{%- endif -%}/{{ awx_rbac.name }}"
  awx.awx.role:
    validate_certs: "{{ validate_certs | default(true) }}"
  # no_log: true
  diff: true


# - name: RBAC Var Cleanup
#   ansible.builtin.set_fact:
#     awx_rbac: null
#     awx_organization_name: null
#     awx_inventory_name: null
#     awx_project_name: null
#     job_template_name: null
