---

- name: Check if AWX Settings files exist
  ansible.builtin.stat:
    path: "{{ file.name }}"
  register: settings_exist
  loop: "{{ settings_files }}"
  loop_control:
    loop_var: file
  when: file.when | default(true)
  vars:
    settings_files:
      # ToDo: check if there is a stat lookup?
      #       if so use to check if host file that matchess group file exists
      #       if so, don't include group file of same name
      - name: "{{ inventory_dir }}/../templates/groups/awx/config-awx-system.json.j2"
        type: template
      - name: "{{ inventory_dir }}/../templates/groups/awx/config-awx-authentication_saml.json.j2"
        type: template
        when: my_awx_config.settings.authentication.enabled | default(false) | bool


- name: Common tasks
  awx.awx.settings:
    controller_host: "{{ nfc_pb_awx_controller_host | default(omit) }}"
    controller_oauthtoken: "{{ nfc_pb_awx_controller_oauthtoken | default(omit) }}"
    controller_username: "{{ nfc_pb_awx_controller_username | default(omit) }}"
    controller_password: "{{ nfc_pb_awx_controller_password | default(omit) }}"
    validate_certs: "{{ validate_certs | default(true) }}"

    settings: "{{ lookup(settings.file.type, settings.file.name) }}"
  loop: "{{ settings_exist.results }}"
  loop_control:
    loop_var: settings
  when: settings.stat.exists
