---

- name: Teams Setup
  awx.awx.team:
    name: "{{ nfc_pb_awx_team.name }}"
    description: "{{ nfc_pb_awx_team.description | default('') }}"
    controller_host: "{{ nfc_pb_awx_controller_host | default(omit) }}"
    controller_oauthtoken: "{{ nfc_pb_awx_controller_oauthtoken | default(omit) }}"
    controller_username: "{{ nfc_pb_awx_controller_username | default(omit) }}"
    controller_password: "{{ nfc_pb_awx_controller_password | default(omit) }}"
    organization: "{{ nfc_pb_awx_organization.name | default('') }}"
    state: "{{ nfc_pb_awx_team.state | default('present') }}"
    validate_certs: "{{ validate_certs | default(true) }}"
  # no_log: true
  diff: true
