---

- name: Workflow
  awx.awx.workflow_job_template:
    controller_host: "{{ nfc_pb_awx_controller_host | default(omit) }}"
    controller_oauthtoken: "{{ nfc_pb_awx_controller_oauthtoken | default(omit) }}"
    controller_username: "{{ nfc_pb_awx_controller_username | default(omit) }}"
    controller_password: "{{ nfc_pb_awx_controller_password | default(omit) }}"
    validate_certs: "{{ validate_certs | default(true) }}"

    name: "{{ workflow_job_template.name }}"
      # description:
      #   - Name of this workflow job template.
      # required: True
      # type: str
    new_name: "{{ workflow_job_template.new_name | default(omit) }}"
      # description:
      #   - Setting this option will change the existing name.
      # type: str
    copy_from: "{{ workflow_job_template.copy_from | default(omit) }}"
      # description:
      #   - Name or id to copy the workflow job template from.
      #   - This will copy an existing workflow job template and change any parameters supplied.
      #   - The new workflow job template name will be the one provided in the name parameter.
      #   - The organization parameter is not used in this, to facilitate copy from one organization to another.
      #   - Provide the id or use the lookup plugin to provide the id if multiple workflow job templates share the same name.
      # type: str
    description: "{{ workflow_job_template.description | default(omit) }}"
      # description:
      #   - Optional description of this workflow job template.
      # type: str
    extra_vars: "{{ workflow_job_template.extra_vars | default(omit) }}"
      # description:
      #   - Variables which will be made available to jobs ran inside the workflow.
      # type: dict
    job_tags: "{{ workflow_job_template.job_tags | default(omit) }}"
      # description:
      #   - Comma separated list of the tags to use for the job template.
      # type: str
    ask_tags_on_launch: "{{ workflow_job_template.ask_tags_on_launch | default(omit) }}"
      # description:
      #   - Prompt user for job tags on launch.
      # type: bool
    organization: "{{ nfc_pb_awx_organization.name | default(omit) }}"
      # description:
      #   - Organization name, ID, or named URL the workflow job template exists in.
      #   - Used to help lookup the object, cannot be modified using this module.
      #   - If not provided, will lookup by name only, which does not work with duplicates.
      # type: str
    allow_simultaneous: "{{ workflow_job_template.allow_simultaneous | default(omit) }}"
      # description:
      #   - Allow simultaneous runs of the workflow job template.
      # type: bool
    ask_variables_on_launch: "{{ workflow_job_template.ask_variables_on_launch | default(omit) }}"
      # description:
      #   - Prompt user for C(extra_vars) on launch.
      # type: bool
    inventory: "{{ workflow_job_template.inventory | default(omit) }}"
      # description:
      #   - Name, ID, or named URL of inventory applied as a prompt, assuming job template prompts for inventory
      # type: str
    limit: "{{ workflow_job_template.limit | default(omit) }}"
      # description:
      #   - Limit applied as a prompt, assuming job template prompts for limit
      # type: str
    scm_branch: "{{ workflow_job_template.scm_branch | default(omit) }}"
      # description:
      #   - SCM branch applied as a prompt, assuming job template prompts for SCM branch
      # type: str
    ask_inventory_on_launch: "{{ workflow_job_template.ask_inventory_on_launch | default(omit) }}"
      # description:
      #   - Prompt user for inventory on launch of this workflow job template
      # type: bool
    ask_scm_branch_on_launch: "{{ workflow_job_template.ask_scm_branch_on_launch | default(omit) }}"
      # description:
      #   - Prompt user for SCM branch on launch of this workflow job template
      # type: bool
    ask_limit_on_launch: "{{ workflow_job_template.ask_limit_on_launch | default(omit) }}"
      # description:
      #   - Prompt user for limit on launch of this workflow job template
      # type: bool
    ask_labels_on_launch: "{{ workflow_job_template.ask_labels_on_launch | default(omit) }}"
      # description:
      #   - Prompt user for labels on launch.
      # type: bool
    ask_skip_tags_on_launch: "{{ workflow_job_template.ask_skip_tags_on_launch | default(omit) }}"
      # description:
      #   - Prompt user for job tags to skip on launch.
      # type: bool
    skip_tags: "{{ workflow_job_template.skip_tags | default(omit) }}"
      # description:
      #   - Comma separated list of the tags to skip for the job template.
      # type: str
    webhook_service: "{{ workflow_job_template.webhook_service | default(omit) }}"
      # description:
      #   - Service that webhook requests will be accepted from
      # type: str
      # choices:
      #   - github
      #   - gitlab
    webhook_credential: "{{ workflow_job_template.webhook_credential | default(omit) }}"
      # description:
      #   - Personal Access Token for posting back the status to the service API
      # type: str
    survey_enabled: "{{ workflow_job_template.survey_enabled | default(omit) }}"
      # description:
      #   - Setting that variable will prompt the user for job type on the
      #     workflow launch.
      # type: bool
    survey_spec: "{{ workflow_job_template.survey_spec | default(omit) }}"
      # description:
      #   - The definition of the survey associated to the workflow.
      # type: dict
    labels: "{{ workflow_job_template.labels | default(omit) }}"
      # description:
      #   - The labels applied to this job template
      #   - Must be created with the labels module first. This will error if the label has not been created.
      # type: list
      # elements: str
    state: "{{ workflow_job_template.state | default('present') }}"
      # description:
      #   - Desired state of the resource.
      # choices:
      #   - present
      #   - absent
      #   - exists
      # default: "present"
      # type: str
    notification_templates_started: "{{ workflow_job_template.notification_templates_started | default(omit) }}"
      # description:
      #   - list of notifications to send on start
      # type: list
      # elements: str
    notification_templates_success: "{{ workflow_job_template.notification_templates_success | default(omit) }}"
      # description:
      #   - list of notifications to send on success
      # type: list
      # elements: str
    notification_templates_error: "{{ workflow_job_template.notification_templates_error | default(omit) }}"
      # description:
      #   - list of notifications to send on error
      # type: list
      # elements: str
    notification_templates_approvals: "{{ workflow_job_template.notification_templates_approvals | default(omit) }}"
      # description:
      #   - list of notifications to send on approval
      # type: list
      # elements: str
    workflow_nodes: "{{ workflow_job_template.workflow_nodes | default(omit) }}"
      # description:
      #   - A json list of nodes and their coresponding options. The following suboptions describe a single node.
      # type: list
      # elements: dict
      # suboptions:
      #   extra_data:
      #     description:
      #       - Variables to apply at launch time.
      #       - Will only be accepted if job template prompts for vars or has a survey asking for those vars.
      #     type: dict
      #     default: {}
      #   inventory:
      #     description:
      #       - Inventory applied as a prompt, if job template prompts for inventory
      #     type: dict
      #     suboptions:
      #       name:
      #         description:
      #           - Name Inventory to be applied to job as launch-time prompts.
      #         type: str
      #       organization:
      #         description:
      #           - Name of key for use in model for organizational reference
      #         type: dict
      #         suboptions:
      #           name:
      #             description:
      #               - The organization of the credentials exists in.
      #             type: str
      #   scm_branch:
      #     description:
      #       - SCM branch applied as a prompt, if job template prompts for SCM branch
      #     type: str
      #   job_type:
      #     description:
      #       - Job type applied as a prompt, if job template prompts for job type
      #     type: str
      #     choices:
      #       - 'run'
      #       - 'check'
      #   job_tags:
      #     description:
      #       - Job tags applied as a prompt, if job template prompts for job tags
      #     type: str
      #   skip_tags:
      #     description:
      #       - Tags to skip, applied as a prompt, if job tempalte prompts for job tags
      #     type: str
      #   limit:
      #     description:
      #       - Limit to act on, applied as a prompt, if job template prompts for limit
      #     type: str
      #   forks:
      #     description:
      #       - The number of parallel or simultaneous processes to use while executing the playbook, if job template prompts for forks
      #     type: int
      #   job_slice_count:
      #     description:
      #       - The number of jobs to slice into at runtime, if job template prompts for job slices.
      #       - Will cause the Job Template to launch a workflow if value is greater than 1.
      #     type: int
      #     default: '1'
      #   timeout:
      #     description:
      #       - Maximum time in seconds to wait for a job to finish (server-side), if job template prompts for timeout.
      #     type: int
      #   execution_environment:
      #     description:
      #       - Name of Execution Environment to be applied to job as launch-time prompts.
      #     type: dict
      #     suboptions:
      #       name:
      #         description:
      #           - Name of Execution Environment to be applied to job as launch-time prompts.
      #           - Uniqueness is not handled rigorously.
      #         type: str
      #   diff_mode:
      #     description:
      #       - Run diff mode, applied as a prompt, if job template prompts for diff mode
      #     type: bool
      #   verbosity:
      #     description:
      #       - Verbosity applied as a prompt, if job template prompts for verbosity
      #     type: str
      #     choices:
      #       - '0'
      #       - '1'
      #       - '2'
      #       - '3'
      #       - '4'
      #       - '5'
      #   all_parents_must_converge:
      #     description:
      #       - If enabled then the node will only run if all of the parent nodes have met the criteria to reach this node
      #     type: bool
      #   identifier:
      #     description:
      #       - An identifier for this node that is unique within its workflow.
      #       - It is copied to workflow job nodes corresponding to this node.
      #     required: True
      #     type: str
      #   state:
      #     description:
      #       - Desired state of the resource.
      #     choices: ["present", "absent"]
      #     default: "present"
      #     type: str
      #   unified_job_template:
      #     description:
      #       - Name of unified job template to run in the workflow.
      #       - Can be a job template, project sync, inventory source sync, etc.
      #       - Omit if creating an approval node (not yet implemented).
      #     type: dict
      #     suboptions:
      #       organization:
      #         description:
      #           - Name of key for use in model for organizational reference
      #           - Only Valid and used if referencing a job template or project sync
      #           - This parameter is mutually exclusive with suboption C(inventory).
      #         type: dict
      #         suboptions:
      #           name:
      #             description:
      #               - The organization of the job template or project sync the node exists in.
      #               - Used for looking up the job template or project sync, not a direct model field.
      #             type: str
      #       inventory:
      #         description:
      #           - Name of key for use in model for organizational reference
      #           - Only Valid and used if referencing an inventory sync
      #           - This parameter is mutually exclusive with suboption C(organization).
      #         type: dict
      #         suboptions:
      #           organization:
      #             description:
      #               - Name of key for use in model for organizational reference
      #             type: dict
      #             suboptions:
      #               name:
      #                 description:
      #                   - The organization of the inventory the node exists in.
      #                   - Used for looking up the job template or project, not a direct model field.
      #                 type: str
      #       name:
      #         description:
      #           - Name of unified job template to run in the workflow.
      #           - Can be a job template, project, inventory source, etc.
      #         type: str
      #       description:
      #         description:
      #           - Optional description of this workflow approval template.
      #         type: str
      #       type:
      #         description:
      #           - Name of unified job template type to run in the workflow.
      #           - Can be a job_template, project, inventory_source, system_job_template, workflow_approval, workflow_job_template.
      #         type: str
      #       timeout:
      #         description:
      #           - The amount of time (in seconds) to wait before Approval is canceled. A value of 0 means no timeout.
      #           - Only Valid and used if referencing an Approval Node
      #         default: 0
      #         type: int
      #   related:
      #     description:
      #       - Related items to this workflow node.
      #     type: dict
      #     suboptions:
      #       always_nodes:
      #         description:
      #           - Nodes that will run after this node completes.
      #           - List of node identifiers.
      #         type: list
      #         elements: dict
      #         suboptions:
      #           identifier:
      #             description:
      #               - Identifier of Node that will run after this node completes given this option.
      #             type: str
      #       success_nodes:
      #         description:
      #           - Nodes that will run after this node on success.
      #           - List of node identifiers.
      #         type: list
      #         elements: dict
      #         suboptions:
      #           identifier:
      #             description:
      #               - Identifier of Node that will run after this node completes given this option.
      #             type: str
      #       failure_nodes:
      #         description:
      #           - Nodes that will run after this node on failure.
      #           - List of node identifiers.
      #         type: list
      #         elements: dict
      #         suboptions:
      #           identifier:
      #             description:
      #               - Identifier of Node that will run after this node completes given this option.
      #             type: str
      #       credentials:
      #         description:
      #           - Credentials to be applied to job as launch-time prompts.
      #           - List of credential names.
      #           - Uniqueness is not handled rigorously.
      #         type: list
      #         elements: dict
      #         suboptions:
      #           name:
      #             description:
      #               - Name Credentials to be applied to job as launch-time prompts.
      #             type: str
      #           organization:
      #             description:
      #               - Name of key for use in model for organizational reference
      #             type: dict
      #             suboptions:
      #               name:
      #                 description:
      #                   - The organization of the credentials exists in.
      #                 type: str
      #       labels:
      #         description:
      #           - Labels to be applied to job as launch-time prompts.
      #           - List of Label names.
      #           - Uniqueness is not handled rigorously.
      #         type: list
      #         elements: dict
      #         suboptions:
      #           name:
      #             description:
      #               - Name Labels to be applied to job as launch-time prompts.
      #             type: str
      #           organization:
      #             description:
      #               - Name of key for use in model for organizational reference
      #             type: dict
      #             suboptions:
      #               name:
      #                 description:
      #                   - The organization of the label node exists in.
      #                 type: str
      #       instance_groups:
      #         description:
      #           - Instance groups to be applied to job as launch-time prompts.
      #           - List of Instance group names.
      #           - Uniqueness is not handled rigorously.
      #         type: list
      #         elements: dict
      #         suboptions:
      #           name:
      #             description:
      #               - Name of Instance groups to be applied to job as launch-time prompts.
      #             type: str
    destroy_current_nodes: "{{ workflow_job_template.destroy_current_nodes | default(true) | bool }}"
      # description:
      #   - Set in order to destroy current workflow_nodes on the workflow.
      #   - This option is used for full workflow update, if not used, nodes not described in workflow will persist and keep current associations and links.
      # type: bool
      # default: False
