---
#
# No Fuss Computing
# https://gitlab.com/nofusscomputing/projects/ansible/ansible_playbooks
#
#
# image: nofusscomputing/ansible-ee >= 0.1.0
#
- name: Set Global Facts
  ansible.builtin.set_fact:
    filename_date_time: "{{ '%Y-%m-%d-%H:%M:%S-%z' | strftime }}"
  when: filename_date_time | default('does_not_exist') == 'does_not_exist'


- name: Backups
  block:

    - name: Fetch Remote User name
      ansible.builtin.command:
        cmd: whoami
      register: remote_username
      changed_when: false
      tags:
        - always


    - name: Set Task Facts
      ansible.builtin.set_fact:
        directory_tasks: '/home/{{ remote_username.stdout | trim }}/task_backup'
        directory_temp_destination: '/home/{{ remote_username.stdout | trim }}/backup'
      tags:
        - always


    - name: Clean existing Task Directory
      ansible.builtin.file:
        name: "{{ directory_tasks }}"
        state: absent
      become: true
      tags:
        - always


    - name: Create Task Directories Directory
      ansible.builtin.file:
        name: "{{ directory_tasks }}"
        state: directory
        owner: root
        group: backup
        mode: '770'
      become: true
      tags:
        - always


    - name: Prepare Encryption Certificate
      ansible.builtin.copy:
        content: "{{ file_encryption_key }}"
        dest: "{{ directory_tasks }}/encryption_certificate"
        owner: root
        group: backup
        mode: '740'
      become: true
      tags:
        - always


    - name: Backup Application
      ansible.builtin.include_tasks:
        file: tasks/backup-application.yaml
        apply:
          tags:
            - always
      loop: "{{ nfc_pb_backup.applications }}"
      loop_control:
        loop_var: application
        label: "{{ application.name }}"
      tags:
        - application


  always:

    - name: Remove Task Temp Files
      ansible.builtin.file:
        name: "{{ directory_tasks }}"
        state: absent
      tags:
        - always
