---

- name: TRACE - Copy Details
  ansible.builtin.debug:
    msg: {
      "source": "{{ directory_source }}/{{ file_name }}",
      "destination": "{{ directory_destination }}"
    }

- name: Copy Remote file to Localhost
  ansible.builtin.fetch:
    src: "{{ directory_source }}/{{ file_name }}"
    dest: "{{ directory_destination }}/"
    flat: true


- name: Set Ownership / Permissions
  ansible.builtin.file:
    name: "{{ directory_destination }}/{{ file_name }}"
    owner: "{{ permissions.owner | default(omit) }}"
    group: "{{ permissions.group | default(omit) }}"
    mode: "{{ permissions.mode | default(omit) }}"
    state: file
  become: true
  delegate_to: localhost
  vars:
    ansible_connection: local
