---

- name: MariaDB Backup
  block:


    - name: Prepare Backup Filename
      ansible.builtin.set_fact:
        file_backup_no_extension_mariadb: "{{ filename_date_time }}-mariadb-{{ database.name }}-{{ inventory_hostname }}"
        directory_database_dump: "{{ directory_temp_destination }}/database-dump"
        cacheable: false


    - name: Ensure no existing Database Dump Directory
      ansible.builtin.file:
        name: "{{ directory_database_dump }}"
        state: absent
      become: true
      delegate_to: |-
        {%- if database.delegate | default('') == 'localhost' -%}
          localhost
        {%- else -%}
          {{ inventory_hostname }}
        {%- endif %}


    - name: Create Database Dump Directory
      ansible.builtin.file:
        name: "{{ directory_database_dump }}"
        state: directory
        owner: root
        group: backup
        mode: '770'
      become: true
      delegate_to: |-
        {%- if database.delegate | default('') == 'localhost' -%}
          localhost
        {%- else -%}
          {{ inventory_hostname }}
        {%- endif %}


    - name: Dump Database
      ansible.builtin.include_tasks:
        file: tasks/modules/community-mysql-mysql_db.yaml
        apply:
          tags:
            - always
      vars:
        task_name_module: Dump Database - {{ database.name }}
        module_database:
          name: "{{ database.name }}"
          host: "{{ database.host | from_yaml }}"
          state: dump
          target: "{{ directory_database_dump }}/{{ database.name }}.sql"
          become: true
          delegate_to: |-
            {%- if database.delegate | default('') == 'localhost' -%}
              localhost
            {%- else -%}
              {{ inventory_hostname }}
            {%- endif %}


    - name: Set Database Dump Permissions
      ansible.builtin.file:
        name: |-
          {% if database.encrypt | default(true) | bool -%}
            {{ file_backup_no_extension_mariadb }}-{{ backup.encryption_algorithm }}.sql.enc
          {%- else -%}
            {{ directory_database_dump }}/{{ database.name }}.sql
          {%- endif %}
        owner: root
        group: backup
        mode: '0740'
        state: file
      become: true
      delegate_to: |-
        {%- if database.delegate | default('') == 'localhost' -%}
          localhost
        {%- else -%}
          {{ inventory_hostname }}
        {%- endif %}


  rescue:


    - name: Remove Failed Backup
      ansible.builtin.file:
        name: "{{ item }}"
        state: absent
      become: true
      loop: "{{ tmp_files }}"
      delegate_to: |-
        {%- if database.delegate | default('') == 'localhost' -%}
          localhost
        {%- else -%}
          {{ inventory_hostname }}
        {%- endif %}
      vars:
        tmp_files:
          - "{{ directory_tasks }}/{{ file_backup_no_extension_mariadb }}.tar.gz"
          - "{{ file_backup_no_extension_mariadb }}-{{ backup.encryption_algorithm }}.sql.enc"


    - name: Task Failed Force Kill Play
      ansible.builtin.assert:
        that:
          - false
        msg: "The Play Failed"
