---

- name: Prepare Backup Filename
  ansible.builtin.set_fact:
    postgresdb_filename_backup: "{{ database.name }}.sql"
    directory_database_dump: "{{ directory_temp_destination }}/database-dump"


- name: Ensure no existing Database Dump Directory
  ansible.builtin.file:
    name: "{{ directory_database_dump }}"
    state: absent
  become: true


- name: Create Database Dump Directory
  ansible.builtin.file:
    name: "{{ directory_database_dump }}"
    state: directory
    owner: root
    group: backup
    mode: '770'
  become: true


- name: Dump an existing database to a file
  community.postgresql.postgresql_db:
    login_host: "{{ database.host.name }}"
    port: "{{ database.host.port | default(omit) }}"
    login_user: "{{ nfc_pb_postgres_username }}"
    login_password: "{{ nfc_pb_postgres_password }}"
    login_unix_socket: "{{ database.host.socket | default(omit) }}"

    name: "{{ database.name }}"
    state: dump
    target: "{{ directory_database_dump }}/{{ postgresdb_filename_backup }}"


- name: Set Database Dump Permissions
  ansible.builtin.file:
    name: "{{ directory_database_dump }}/{{ postgresdb_filename_backup }}"
    owner: root
    group: backup
    mode: '0740'
    state: file
  become: true
