---
- name: Kubernetes Master Hosts
  hosts: kubernetes_master
  gather_facts: true
  become: true


  roles:

    - name: Install/Configure Kubernetes Prime Master Node
      role: nfc_kubernetes
      when:
        kubernetes_config.cluster.prime.name == inventory_hostname


    - name: Install/Configure Kubernetes on remaining Master Nodes
      role: nfc_kubernetes
      when:
        kubernetes_config.cluster.prime.name != inventory_hostname


  tasks:

    - ansible.builtin.debug:
        msg: "{{ configured_directory_root | default('') }}"
    # ToDo: Remove this when nfc_common made public and has been refactored to be more efficient
    - name: Temp Tasks from Common
      tags:
        - always
      # when: >
      #   configured_directory_root | default('') == ''
      block:


        - name: Find directory root
          ansible.builtin.shell: |
            ROOT_DIR_orig={{ playbook_dir | dirname }}

            if [ -f {{ playbook_dir | dirname | dirname }}/.inventory_root ]; then
              ROOT_DIR={{ playbook_dir | dirname | dirname }}
            fi;

            if [ "0$ROOT_DIR" == "0" ]; then

              if [ -f $PWD/.inventory_root ]; then

                ROOT_DIR=$(echo -n $PWD)

              fi;

            fi;

            if [ "0$ROOT_DIR" == "0" ]; then

              if [ -f /runner/.inventory_root ]; then

                ROOT_DIR=/runner

              fi;

            fi;

            if [ "0$ROOT_DIR" == "0" ]; then

              if [ -f /runner/project/.inventory_root ]; then

                ROOT_DIR=/runner/project

              fi;

            fi;

            if [ "0$ROOT_DIR" == "0" ]; then

              if [ -f /workdir/.inventory_root ]; then

                ROOT_DIR=/workdir

              fi;

            fi;

            echo -n $ROOT_DIR
          args:
            executable: /bin/bash
          register: directory_root_search
          delegate_to: localhost
          connection: local
          become: false
          changed_when: false
          tags:
            - always

        - name: Set initial common facts
          ansible.builtin.set_fact:
            configured_directory_root: "{{ directory_root_search.stdout }}"
            cacheable: true
          tags:
            - always


    - name: Add Kubernetes Manifest Files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/var/lib/rancher/k3s/server/manifests/{{ item | basename | lower | replace('_', '-') }}"
        mode: '700'
        owner: root
        group: root
      with_fileglob: '{{ configured_directory_root }}/files/{{ inventory_hostname }}/*-manifest-*.yaml'
      when: >
        kubernetes_config.cluster.prime.name == inventory_hostname
          and
        kubernetes_type == 'k3s'


    - name: Expand and add Kubernetes template manifest files
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/var/lib/rancher/k3s/server/manifests/{{ item | basename | lower | replace('_', '-') }}"
        mode: '700'
        owner: root
        group: root
      with_fileglob: '{{ configured_directory_root }}/templates/{{ inventory_hostname }}/*-manifest-*.yaml'
      when: >
        kubernetes_config.cluster.prime.name == inventory_hostname
          and
        kubernetes_type == 'k3s'
      diff: true
