---

- name: Role Mapping Configuration
  community.general.keycloak_client_rolemapping:
    auth_keycloak_url: "{{ nfc_pb_keycloak_auth_keycloak_url }}"
    auth_realm: "{{ nfc_pb_keycloak_auth_realm }}"
    auth_username: "{{ nfc_pb_keycloak_auth_username }}"
    auth_password: "{{ nfc_pb_keycloak_auth_password }}"
    validate_certs: "{{ nfc_pb_keycloak_validate_certs | default(true) }}"

    state: "{{ keycloak_client_rolemapping.state | default('present') }}"
        # description:
        #     - State of the client_rolemapping.
        #     - On V(present), the client_rolemapping will be created if it does not yet exist, or updated with the parameters you provide.
        #     - On V(absent), the client_rolemapping will be removed if it exists.
        # default: 'present'
        # type: str
        # choices:
        #     - present
        #     - absent

    realm: "{{ keycloak_realm.realm }}"
        # type: str
        # description:
        #     - They Keycloak realm under which this role_representation resides.
        # default: 'master'

    group_name: "{{ keycloak_client_rolemapping.group_name }}"
        # type: str
        # description:
        #     - Name of the group to be mapped.
        #     - This parameter is required (can be replaced by gid for less API call).

    parents: "{{ keycloak_client_rolemapping.parents | default(omit) }}"
        # version_added: "7.1.0"
        # type: list
        # description:
        #     - List of parent groups for the group to handle sorted top to bottom.
        #     - >-
        #       Set this if your group is a subgroup and you do not provide the GID in O(gid).
        # elements: dict
        # suboptions:
        #   id:
        #     type: str
        #     description:
        #       - Identify parent by ID.
        #       - Needs less API calls than using O(parents[].name).
        #       - A deep parent chain can be started at any point when first given parent is given as ID.
        #       - Note that in principle both ID and name can be specified at the same time
        #         but current implementation only always use just one of them, with ID
        #         being preferred.
        #   name:
        #     type: str
        #     description:
        #       - Identify parent by name.
        #       - Needs more internal API calls than using O(parents[].id) to map names to ID's under the hood.
        #       - When giving a parent chain with only names it must be complete up to the top.
        #       - Note that in principle both ID and name can be specified at the same time
        #         but current implementation only always use just one of them, with ID
        #         being preferred.
    gid: "{{ keycloak_client_rolemapping.gid | default(omit) }}"
        # type: str
        # description:
        #     - Id of the group to be mapped.
        #     - This parameter is not required for updating or deleting the rolemapping but
        #       providing it will reduce the number of API calls required.

    client_id: "{{ keycloak_client.client_id | default(omit) }}"
        # type: str
        # description:
        #     - Name of the client to be mapped (different than O(cid)).
        #     - This parameter is required (can be replaced by cid for less API call).

    cid: "{{ keycloak_client_rolemapping.cid | default(omit) }}"
        # type: str
        # description:
        #     - Id of the client to be mapped.
        #     - This parameter is not required for updating or deleting the rolemapping but
        #       providing it will reduce the number of API calls required.

    roles: "{{ keycloak_client_rolemapping.roles | default(omit) }}"
        # description:
        #     - Roles to be mapped to the group.
        # type: list
        # elements: dict
        # suboptions:
        #     name:
        #         type: str
        #         description:
        #             - Name of the role_representation.
        #             - This parameter is required only when creating or updating the role_representation.
        #     id:
        #         type: str
        #         description:
        #             - The unique identifier for this role_representation.
        #             - This parameter is not required for updating or deleting a role_representation but
        #               providing it will reduce the number of API calls required.
  diff: true
